### ISSUE TITLE
fault-detector container keep restarting

### ISSUE THREAD

**Issue by huahuayu** [smartcontracts/simple-optimism-node#20]
Hi, I use the docker-compose file today, the fault-detector container keeps restarting, other containers seems fine.

```text
> @eth-optimism/fault-detector@0.2.5 start
> ts-node ./src/service.ts

{"level":30,"time":1662028252752,"msg":"starting app server"}
{"level":30,"time":1662028252780,"port":7300,"hostname":"0.0.0.0","msg":"app server started"}
{"level":30,"time":1662028252780,"msg":"initializing service"}
{"level":30,"time":1662028252893,"msg":"finding appropriate starting height"}
{"level":30,"time":1662028258782,"log":"172.19.0.2 - GET /metrics HTTP/1.1 200 - - 5.839 ms\n","msg":"server log"}
{"level":30,"time":1662028273772,"log":"172.19.0.2 - GET /metrics HTTP/1.1 200 - - 2.641 ms\n","msg":"server log"}
{"level":30,"time":1662028288772,"log":"172.19.0.2 - GET /metrics HTTP/1.1 200 - - 2.714 ms\n","msg":"server log"}
{"level":30,"time":1662028303772,"log":"172.19.0.2 - GET /metrics HTTP/1.1 200 - - 2.466 ms\n","msg":"server log"}
{"level":30,"time":1662028318774,"log":"172.19.0.2 - GET /metrics HTTP/1.1 200 - - 3.302 ms\n","msg":"server log"}
{"level":30,"time":1662028333773,"log":"172.19.0.2 - GET /metrics HTTP/1.1 200 - - 2.367 ms\n","msg":"server log"}
{"level":30,"time":1662028348775,"log":"172.19.0.2 - GET /metrics HTTP/1.1 200 - - 3.218 ms\n","msg":"server log"}
{"level":30,"time":1662028363774,"log":"172.19.0.2 - GET /metrics HTTP/1.1 200 - - 3.582 ms\n","msg":"server log"}
/opt/optimism/node_modules/@ethersproject/providers/node_modules/@ethersproject/logger/src.ts/index.ts:261
        const error: any = new Error(message);
                           ^
Error: timeout (requestBody="{\"method\":\"eth_getLogs\",\"params\":[{\"fromBlock\":\"0x0\",\"toBlock\":\"latest\",\"address\":\"0xbe5dab4a2e9cd0f27300db4ab94bee3a233aeb19\",\"topics\":[\"0x16be4c5129a4e03cf3350262e181dc02ddfb4a6008d925368c0899fcd97ca9c5\",\"0x000000000000000000000000000000000000000000000000000000000000312e\"]}],\"id\":53,\"jsonrpc\":\"2.0\"}", requestMethod="POST", timeout=120000, url="http://192.168.2.36:54102", code=TIMEOUT, version=web/5.6.1)
    at Logger.makeError (/opt/optimism/node_modules/@ethersproject/providers/node_modules/@ethersproject/logger/src.ts/index.ts:261:28)
    at Timeout._onTimeout (/opt/optimism/node_modules/@ethersproject/providers/node_modules/@ethersproject/web/src.ts/index.ts:216:35)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7) {
  reason: 'timeout',
  code: 'TIMEOUT',
  requestBody: '{"method":"eth_getLogs","params":[{"fromBlock":"0x0","toBlock":"latest","address":"0xbe5dab4a2e9cd0f27300db4ab94bee3a233aeb19","topics":["0x16be4c5129a4e03cf3350262e181dc02ddfb4a6008d925368c0899fcd97ca9c5","0x000000000000000000000000000000000000000000000000000000000000312e"]}],"id":53,"jsonrpc":"2.0"}',
  requestMethod: 'POST',
  timeout: 120000,
  url: 'http://192.168.2.36:54102'
}
npm ERR! Lifecycle script `start` failed with error:
npm ERR! Error: command failed
npm ERR!   in workspace: @eth-optimism/fault-detector@0.2.5
npm ERR!   at location: /opt/optimism/packages/fault-detector

> @eth-optimism/fault-detector@0.2.5 start
> ts-node ./src/service.ts
```

If my L1 url is a local area network, it can't be accessed from the container right? My config is like this

```text
# Network to run the node on ("mainnet" or "goerli")
NETWORK_NAME=mainnet

# Reference L2 node to run healthcheck against
HEALTHCHECK__REFERENCE_RPC_PROVIDER=https://opt-mainnet.g.alchemy.com/v2/$api-key

# L1 node to run fault detection against
FAULT_DETECTOR__L1_RPC_PROVIDER=http://192.168.2.36:54102

# L1 node to get chain data from
DATA_TRANSPORT_LAYER__L1_RPC_ENDPOINT=http://192.168.2.36:54102
```

**Comment by smartcontracts** [comment]
Fixed upstream
