### ISSUE TITLE
optimism-mainnet dtl start failed

### ISSUE THREAD

**Issue by m1iktea** [smartcontracts/simple-optimism-node#43]
## Log
```
errexit         on
noglob          off
ignoreeof       off
monitor         off
noexec          off
xtrace          off
verbose         off
noclobber       off
allexport       off
notify          off
nounset         off
vi              off
pipefail        off
{"level":30,"time":1675648691697,"msg":"Service is starting..."}
{"level":30,"time":1675648691699,"msg":"Service is initializing..."}
{"level":30,"time":1675648691699,"msg":"Initializing L1 Data Transport Service..."}
{"level":30,"time":1675648691745,"msg":"L2 chain ID is: 10"}
{"level":30,"time":1675648691745,"msg":"BSS HF1 will activate at: 2824317"}
{"level":30,"time":1675648691762,"msg":"Service is initializing..."}
{"level":30,"time":1675648691778,"defaultBackend":"l1","l1GasPriceBackend":"l1","msg":"HTTP Server Options"}
{"level":30,"time":1675648691778,"url":"http://ethereum-mainnet","msg":"HTTP Server L1 RPC Provider initialized"}
{"level":30,"time":1675648691778,"url":"http://ethereum-mainnet","msg":"HTTP Server L2 RPC Provider initialized"}
{"level":30,"time":1675648691779,"msg":"Service has initialized."}
{"level":30,"time":1675648691779,"msg":"Service is initializing..."}
{"level":30,"time":1675648691823,"addressManager":"0xdE1FCfB0851916CA5101820A69b13a4E276bd81F","msg":"Using AddressManager"}
Well, that's that. We ran into a fatal error. Here's the dump. Goodbye!
/opt/optimism/packages/data-transport-layer/dist/src/services/l1-ingestion/service.js:94
            throw new Error(`Provided AddressManager doesn't have any code: ${Lib_AddressManager.address}`);
                  ^
Error: Provided AddressManager doesn't have any code: 0xdE1FCfB0851916CA5101820A69b13a4E276bd81F
    at L1IngestionService._init (/opt/optimism/packages/data-transport-layer/dist/src/services/l1-ingestion/service.js:94:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async L1IngestionService.init (/opt/optimism/packages/common-ts/dist/base-service/base-service.js:22:9)
    at async L1DataTransportService._init (/opt/optimism/packages/data-transport-layer/dist/src/services/main/service.js:61:13)
    at async L1DataTransportService.init (/opt/optimism/packages/common-ts/dist/base-service/base-service.js:22:9)
    at async L1DataTransportService.start (/opt/optimism/packages/common-ts/dist/base-service/base-service.js:31:9)
    at async /opt/optimism/packages/data-transport-layer/dist/src/services/run.js:78:9
```

## Config

I use default env file , only `.env` file has been modified

.env
```
###############################################################################
#                                ↓ REQUIRED ↓                                 #
###############################################################################

# Network to run the node on ("mainnet" or "goerli")
NETWORK_NAME=mainnet

# Type of node to run ("full" or "archive"), note that "archive" is 10x bigger
NODE_TYPE=full

# Where to sync data from ("l1" or "l2"), see README for more information
SYNC_SOURCE=l1

# Reference L2 node to run healthcheck against
HEALTHCHECK__REFERENCE_RPC_PROVIDER=https://optimism-mainnet.public.blastapi.io

# L1 node to run fault detection against
FAULT_DETECTOR__L1_RPC_PROVIDER=http://ethereum-mainnet

# Node to get chain data from (if SYNC_SOURCE is "l1" then use L1 node, etc.)
DATA_TRANSPORT_LAYER__RPC_ENDPOINT=http://ethereum-mainnet

###############################################################################
#                                ↓ OPTIONAL ↓                                 #
###############################################################################

# Feel free to customize your image tag if you want, uses "latest" by default
# See here for all avalabe images: https://hub.docker.com/u/ethereumoptimism
IMAGE_TAG__L2GETH=0.5.31
IMAGE_TAG__DTL=0.5.50
IMAGE_TAG__HEALTCHECK=
IMAGE_TAG__FAULT_DETECTOR=0.5.0
IMAGE_TAG__PROMETHEUS=
IMAGE_TAG__GRAFANA=
IMAGE_TAG__INFLUXDB=1.6

# Exposed server ports (must be unique)
# See docker-compose.yml for default values
PORT__L2GETH_HTTP=
PORT__L2GETH_WS=
PORT__DTL=
PORT__HEALTHCHECK_METRICS=
PORT__FAULT_DETECTOR_METRICS=
PORT__PROMETHEUS=
PORT__GRAFANA=
PORT__INFLUXDB=
```

`http://ethereum-mainnet` is a readable service in my kubernetes cluster , and i use almost the same way to start goerli net , there is no such problem in dtl service . 

Need help , Thx

**Comment by smartcontracts** [comment]
Hmmm... hard to figure out what's going on here without more info. Can you double check that `http://ethereum-mainnet` is actually connected to Ethereum mainnet and you aren't accidentally connected to another network instead?

**Comment by m1iktea** [comment]
well, i try to set `FAULT_DETECTOR__L1_RPC_PROVIDER`,`DATA_TRANSPORT_LAYER__RPC_ENDPOINT` as public rpc endpoint `https://rpc.ankr.com/eth` and clean data dir , dtl service no longer has the above problems.

but l2geth is stuck.  `Database compacting, degraded performance database=/geth/geth/chaindata` , is that ok?

## geth log
```
+ echo running /scripts/l2geth-init.sh
+ GETH_DATA_DIR=/geth
+ GETH_CHAINDATA_DIR=/geth/geth/chaindata
+ GETH_KEYSTORE_DIR=/geth/keystore
running /scripts/l2geth-init.sh
+ '[' '!' -d /geth/keystore ]
+ echo '/geth/keystore missing, running account import'
/geth/keystore missing, running account import
+ echo -n pwd
+ echo -n 6587ae678cf4fc9a33000cdbf9f35226b71dcc6a4684a31203241f9bcfd55d27
+ geth account import '--datadir=/geth' '--password=/geth/password' /geth/block-signer-key
INFO [02-07|07:21:57.796] Maximum peer count                       ETH=50 LES=0 total=50
INFO [02-07|07:21:57.796] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
Address: {00000398232e2064f896018496b4b44b3d62751f}
+ echo 'get account import complete'
+ '[' '!' -d /geth/geth/chaindata ]
+ echo '/geth/geth/chaindata missing, running init'
+ geth init '--datadir=/geth' https://storage.googleapis.com/optimism/mainnet/genesis-berlin.json 0x106b0a3247ca54714381b1109e82cc6b7e32fd79ae56fbcc2e7b1541122f84ea
get account import complete
/geth/geth/chaindata missing, running init
INFO [02-07|07:22:01.185] Fetching genesis file                    url=https://storage.googleapis.com/optimism/mainnet/genesis-berlin.json
INFO [02-07|07:22:42.644] Maximum peer count                       ETH=50 LES=0 total=50
INFO [02-07|07:22:42.644] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
INFO [02-07|07:22:42.645] Allocated cache and file handles         database=/geth/geth/chaindata cache=16.00MiB handles=16
INFO [02-07|07:22:50.294] Writing custom genesis block 
WARN [02-07|07:30:38.432] Database compacting, degraded performance database=/geth/geth/chaindata
WARN [02-07|07:31:38.451] Database compacting, degraded performance database=/geth/geth/chaindata
WARN [02-07|07:32:44.473] Database compacting, degraded performance database=/geth/geth/chaindata
WARN [02-07|07:34:29.507] Database compacting, degraded performance database=/geth/geth/chaindata
WARN [02-07|07:35:29.527] Database compacting, degraded performance database=/geth/geth/chaindata
WARN [02-07|07:36:35.547] Database compacting, degraded performance database=/geth/geth/chaindata
WARN [02-07|07:37:35.565] Database compacting, degraded performance database=/geth/geth/chaindata
WARN [02-07|07:38:35.595] Database compacting, degraded performance database=/geth/geth/chaindata
WARN [02-07|07:39:35.619] Database compacting, degraded performance database=/geth/geth/chaindata
WARN [02-07|07:40:35.640] Database compacting, degraded performance database=/geth/geth/chaindata
WARN [02-07|07:41:35.659] Database compacting, degraded performance database=/geth/geth/chaindata
WARN [02-07|07:42:35.675] Database compacting, degraded performance database=/geth/geth/chaindata
WARN [02-07|07:43:35.696] Database compacting, degraded performance database=/geth/geth/chaindata
WARN [02-07|07:44:35.713] Database compacting, degraded performance database=/geth/geth/chaindata
```

**Comment by m1iktea** [comment]
after long time database compacting , mainnet sync has now returned to normal
