### ISSUE TITLE
I still stuck in 4061223

### ISSUE THREAD

**Issue by UranusLin** [smartcontracts/simple-optimism-node#50]
Hi I checkout repo and edit.env then 
```
docker-compose up -d 
```
but still stuck in 4061223
this is my .env setting
```
###############################################################################
#                                ↓ REQUIRED ↓                                 #
###############################################################################

# Network to run the node on ("mainnet" or "goerli")
NETWORK_NAME=goerli

# Type of node to run ("full" or "archive"), note that "archive" is 10x bigger
NODE_TYPE=full

###############################################################################
#                            ↓ REQUIRED (LEGACY) ↓                            #
###############################################################################

# Where to sync data from ("l1" or "l2"), see README
SYNC_SOURCE=l1

# Reference L2 node to run healthcheck against
HEALTHCHECK__REFERENCE_RPC_PROVIDER=http://[my old op L2 node ip] :9991

# L1 node to run fault detection against
FAULT_DETECTOR__L1_RPC_PROVIDER=http://[my ethereum L1 node ip]:7799

# Node to get chain data from (if SYNC_SOURCE is "l1" then use L1 node, etc.)
DATA_TRANSPORT_LAYER__RPC_ENDPOINT=http://[my ethereum L1 node ip]:7799

###############################################################################
#                            ↓ REQUIRED (BEDROCK) ↓                           #
###############################################################################

# Where to get the Bedrock database ("download" or "migration"), see README
BEDROCK_SOURCE=download

# L1 node that the op-node (Bedrock) will get chain data from
OP_NODE__RPC_ENDPOINT=http://[my ethereum L1 node ip]:7799

# Type of RPC that op-node is connected to, see README
OP_NODE__RPC_TYPE=basic

###############################################################################
#                                ↓ OPTIONAL ↓                                 #
###############################################################################

# Feel free to customize your image tag if you want, uses "latest" by default
# See here for all avalabe images: https://hub.docker.com/u/ethereumoptimism
IMAGE_TAG__L2GETH=
IMAGE_TAG__DTL=
IMAGE_TAG__HEALTCHECK=
IMAGE_TAG__FAULT_DETECTOR=
IMAGE_TAG__PROMETHEUS=
IMAGE_TAG__GRAFANA=
IMAGE_TAG__INFLUXDB=

# Exposed server ports (must be unique)
# See docker-compose.yml for default values
PORT__L2GETH_HTTP=
PORT__L2GETH_WS=
PORT__DTL=
PORT__HEALTHCHECK_METRICS=
PORT__HEALTHCHECK_BEDROCK_METRICS=
PORT__FAULT_DETECTOR_METRICS=
PORT__PROMETHEUS=
PORT__GRAFANA=
PORT__INFLUXDB=
PORT__TORRENT_UI=
PORT__TORRENT=
PORT__OP_GETH_HTTP=
PORT__OP_GETH_WS=
```
is any step I need to do to start bedrock?
Please to help my to find out problem thanks.

**Comment by VetchM** [comment]
Same problem here, the ndoes i'm using are from alchemy.

**Comment by almukhametovd** [comment]
@VetchM @UranusLin after prebedtock sync, bedrock blocks will be available here: **op-geth** service (run `docker ps` to see all containers) on 9993 port.

**Comment by VetchM** [comment]
@almukhametovd  I checked `op-geth`, then found out the `bedrock-init` service was not running at all. Could you help me on this? Here are part of the logs:
```py
+ source ./scripts/utils.sh
+ INITIALIZED_FLAG=/shared/initialized.txt
+ BEDROCK_JWT_PATH=/shared/jwt.txt
+ GETH_DATA_DIR=/geth
+ TORRENTS_DIR=/torrents/goerli
+ true
++ config bedrock/goerli/ready
+++ cast call 0xcbebc5ba53ff12165239cbb3d310fda2236d6ad2 'config(address,string)(string)' 0x68108902De3A5031197a6eB3b74b3b033e8E8e4d bedrock/goerli/ready --rpc-url https://goerli.infura.io/v3/84842078b09946638c03157f83405213
++ echo true
+ BEDROCK_FLAG=true
+ '[' true == true ']'
+ break
++ config bedrock/goerli/terminal-height
+++ cast call 0xcbebc5ba53ff12165239cbb3d310fda2236d6ad2 'config(address,string)(string)' 0x68108902De3A5031197a6eB3b74b3b033e8E8e4d bedrock/goerli/terminal-height --rpc-url https://goerli.infura.io/v3/84842078b09946638c03157f83405213
++ echo 4061223
+ TERMINAL_HEIGHT=4061223
++ config bedrock/goerli/bedrock-magnet
+++ cast call 0xcbebc5ba53ff12165239cbb3d310fda2236d6ad2 'config(address,string)(string)' 0x68108902De3A5031197a6eB3b74b3b033e8E8e4d bedrock/goerli/bedrock-magnet --rpc-url https://goerli.infura.io/v3/84842078b09946638c03157f83405213
++ echo 'magnet:?xt=urn:btih:3f0b0ae9f4952696bc2a878f102c248d29e945dc&dn=bedrock.tar'
+ BEDROCK_TAR_MAGNET='magnet:?xt=urn:btih:3f0b0ae9f4952696bc2a878f102c248d29e945dc&dn=bedrock.tar'
++ config bedrock/goerli/witness-magnet
+++ cast call 0xcbebc5ba53ff12165239cbb3d310fda2236d6ad2 'config(address,string)(string)' 0x68108902De3A5031197a6eB3b74b3b033e8E8e4d bedrock/goerli/witness-magnet --rpc-url https://goerli.infura.io/v3/84842078b09946638c03157f83405213
++ echo 'magnet:?xt=urn:btih:50a7e9a8a773a26a43838470747f6e7f28e2d4f2&dn=witness.tar'
+ WITNESS_TAR_MAGNET='magnet:?xt=urn:btih:50a7e9a8a773a26a43838470747f6e7f28e2d4f2&dn=witness.tar'
+ '[' -e /shared/initialized.txt ']'
+ '[' download == download ']'
+ BEDROCK_TAR_PATH=/downloads/bedrock.tar
+ BEDROCK_TMP_PATH=/bedrock-tmp
+ echo 'Downloading bedrock.tar...'
Downloading bedrock.tar...
+ torrent 'magnet:?xt=urn:btih:3f0b0ae9f4952696bc2a878f102c248d29e945dc&dn=bedrock.tar'
+ python3 ./scripts/torrent.py 'magnet:?xt=urn:btih:3f0b0ae9f4952696bc2a878f102c248d29e945dc&dn=bedrock.tar'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/qbittorrentapi/decorators.py", line 92, in wrapper

    return func(client, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/qbittorrentapi/app.py", line 145, in app_web_api_version
    return self._MOCK_WEB_API_VERSION or self._get(
  File "/usr/local/lib/python3.10/dist-packages/qbittorrentapi/request.py", line 354, in _get
    return self._request_manager(
  File "/usr/local/lib/python3.10/dist-packages/qbittorrentapi/request.py", line 466, in _request_manager
    return self._request(
  File "/usr/local/lib/python3.10/dist-packages/qbittorrentapi/request.py", line 543, in _request
    self._handle_error_responses(data, params, response)
  File "/usr/local/lib/python3.10/dist-packages/qbittorrentapi/request.py", line 763, in _handle_error_responses
    raise Forbidden403Error(response.text)
qbittorrentapi.exceptions.Forbidden403Error: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "//./scripts/torrent.py", line 20, in <module>
    qbt.torrents.add(urls=magnet_uri)
  File "/usr/local/lib/python3.10/dist-packages/qbittorrentapi/torrents.py", line 630, in add
    return self._client.torrents_add(
  File "/usr/local/lib/python3.10/dist-packages/qbittorrentapi/decorators.py", line 92, in wrapper
    return func(client, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/qbittorrentapi/torrents.py", line 1256, in torrents_add
    api_version = self.app_web_api_version()
  File "/usr/local/lib/python3.10/dist-packages/qbittorrentapi/decorators.py", line 95, in wrapper
    client.auth_log_in(**get_requests_kwargs(**kwargs))
  File "/usr/local/lib/python3.10/dist-packages/qbittorrentapi/auth.py", line 106, in auth_log_in
    raise LoginFailed()
qbittorrentapi.exceptions.LoginFailed
```

**Comment by UranusLin** [comment]
@almukhametovd thanks! It's syncing now!

**Comment by smartcontracts** [comment]
Closing since this appears to be fixed
