### ISSUE TITLE
Forbidden403Error

### ISSUE THREAD

**Issue by VetchM** [smartcontracts/simple-optimism-node#60]
The `bedrock-init` service printed these logs, why am i getting `Forbidden403Error`? Does it mean the IP of my server is baned? Or i misconfiged something?

```py
+ source ./scripts/utils.sh
+ INITIALIZED_FLAG=/shared/initialized.txt
+ BEDROCK_JWT_PATH=/shared/jwt.txt
+ GETH_DATA_DIR=/geth
+ TORRENTS_DIR=/torrents/goerli
+ true
++ config bedrock/goerli/ready
+++ cast call 0xcbebc5ba53ff12165239cbb3d310fda2236d6ad2 'config(address,string)(string)' 0x68108902De3A5031197a6eB3b74b3b033e8E8e4d bedrock/goerli/ready --rpc-url https://goerli.infura.io/v3/84842078b09946638c03157f83405213
++ echo true
+ BEDROCK_FLAG=true
+ '[' true == true ']'
+ break
++ config bedrock/goerli/terminal-height
+++ cast call 0xcbebc5ba53ff12165239cbb3d310fda2236d6ad2 'config(address,string)(string)' 0x68108902De3A5031197a6eB3b74b3b033e8E8e4d bedrock/goerli/terminal-height --rpc-url https://goerli.infura.io/v3/84842078b09946638c03157f83405213
++ echo 4061223
+ TERMINAL_HEIGHT=4061223
++ config bedrock/goerli/bedrock-magnet
+++ cast call 0xcbebc5ba53ff12165239cbb3d310fda2236d6ad2 'config(address,string)(string)' 0x68108902De3A5031197a6eB3b74b3b033e8E8e4d bedrock/goerli/bedrock-magnet --rpc-url https://goerli.infura.io/v3/84842078b09946638c03157f83405213
++ echo 'magnet:?xt=urn:btih:3f0b0ae9f4952696bc2a878f102c248d29e945dc&dn=bedrock.tar'
+ BEDROCK_TAR_MAGNET='magnet:?xt=urn:btih:3f0b0ae9f4952696bc2a878f102c248d29e945dc&dn=bedrock.tar'
++ config bedrock/goerli/witness-magnet
+++ cast call 0xcbebc5ba53ff12165239cbb3d310fda2236d6ad2 'config(address,string)(string)' 0x68108902De3A5031197a6eB3b74b3b033e8E8e4d bedrock/goerli/witness-magnet --rpc-url https://goerli.infura.io/v3/84842078b09946638c03157f83405213
++ echo 'magnet:?xt=urn:btih:50a7e9a8a773a26a43838470747f6e7f28e2d4f2&dn=witness.tar'
+ WITNESS_TAR_MAGNET='magnet:?xt=urn:btih:50a7e9a8a773a26a43838470747f6e7f28e2d4f2&dn=witness.tar'
+ '[' -e /shared/initialized.txt ']'
+ '[' download == download ']'
+ BEDROCK_TAR_PATH=/downloads/bedrock.tar
+ BEDROCK_TMP_PATH=/bedrock-tmp
+ echo 'Downloading bedrock.tar...'
Downloading bedrock.tar...
+ torrent 'magnet:?xt=urn:btih:3f0b0ae9f4952696bc2a878f102c248d29e945dc&dn=bedrock.tar'
+ python3 ./scripts/torrent.py 'magnet:?xt=urn:btih:3f0b0ae9f4952696bc2a878f102c248d29e945dc&dn=bedrock.tar'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/qbittorrentapi/decorators.py", line 92, in wrapper

    return func(client, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/qbittorrentapi/app.py", line 145, in app_web_api_version
    return self._MOCK_WEB_API_VERSION or self._get(
  File "/usr/local/lib/python3.10/dist-packages/qbittorrentapi/request.py", line 354, in _get
    return self._request_manager(
  File "/usr/local/lib/python3.10/dist-packages/qbittorrentapi/request.py", line 466, in _request_manager
    return self._request(
  File "/usr/local/lib/python3.10/dist-packages/qbittorrentapi/request.py", line 543, in _request
    self._handle_error_responses(data, params, response)
  File "/usr/local/lib/python3.10/dist-packages/qbittorrentapi/request.py", line 763, in _handle_error_responses
    raise Forbidden403Error(response.text)
qbittorrentapi.exceptions.Forbidden403Error: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "//./scripts/torrent.py", line 20, in <module>
    qbt.torrents.add(urls=magnet_uri)
  File "/usr/local/lib/python3.10/dist-packages/qbittorrentapi/torrents.py", line 630, in add
    return self._client.torrents_add(
  File "/usr/local/lib/python3.10/dist-packages/qbittorrentapi/decorators.py", line 92, in wrapper
    return func(client, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/qbittorrentapi/torrents.py", line 1256, in torrents_add
    api_version = self.app_web_api_version()
  File "/usr/local/lib/python3.10/dist-packages/qbittorrentapi/decorators.py", line 95, in wrapper
    client.auth_log_in(**get_requests_kwargs(**kwargs))
  File "/usr/local/lib/python3.10/dist-packages/qbittorrentapi/auth.py", line 106, in auth_log_in
    raise LoginFailed()
qbittorrentapi.exceptions.LoginFailed
```

**Comment by VetchM** [comment]
I recloned repo and restarted my node, the problem is gone now, thanks
