### ISSUE TITLE
Unstable and misleading documentation

### ISSUE THREAD

**Issue by allquantor** [smartcontracts/simple-optimism-node#86]
-  The documentation says 

```
pen .env with your editor of choice and fill out the environment variables listed inside that file. You MUST fill in all variables in the REQUIRED (LEGACY) OR REQUIRED (BEDROCK) sections. If you wish to run both a legacy node and a Bedrock node at the same time, you MUST fill in BOTH sections.
```

this is WRONG. Setup tries bedrock and fails if bedrock is not configured:

```
simple-optimism-node-healthcheck-1  | /opt/optimism/packages/common-ts/src/base-service/base-service-v2.ts:244
simple-optimism-node-healthcheck-1  |         throw new Error(`missing required option: ${optionName}`)
simple-optimism-node-healthcheck-1  |               ^
simple-optimism-node-healthcheck-1  | Error: missing required option: referenceRpcProvider
simple-optimism-node-healthcheck-1  |     at new BaseServiceV2 (/opt/optimism/packages/common-ts/src/base-service/base-service-v2.ts:244:15)
simple-optimism-node-healthcheck-1  |     at new HealthcheckService (/opt/optimism/packages/replica-healthcheck/src/service.ts:37:5)
```
- Documentation refers to node configurations from alchemy; whatever here, however, needs to outline how those be used. No examples of the variable input format. Very confusing to have multiple input variables for essentially the exact value of a source node.

**Comment by cryptothink629** [comment]
they said they are lazy, and I am shorting the $OP : )

**Comment by smartcontracts** [comment]
Are you running with `--profile legacy`? If you run with `--profile current` or without the profile option then it'll try to run a Bedrock node. If you only want to run a legacy node then you need to run with `--profile legacy`. See the Profiles section of the README.

> Documentation refers to node configurations from alchemy; whatever here, however, needs to outline how those be used. No examples of the variable input format

I'm not sure what you mean by this
