### ISSUE TITLE
Fault detector errrors

### ISSUE THREAD

**Issue by stas** [smartcontracts/simple-optimism-node#9]
Hi there,
and first of all, thanks a lot for setting up the project! :bow: 

We (Velodrome Finance), are exploring the idea of setting up a node on fly.io for project use. Most of the stuff worked well, but we're getting the errors below. I'm not sure what causes the situation, as the sync looks 100% up-to-date with L1 blocks, so I'm reaching out to see if there's anything we've missed.

Appreciate any feedback :heart: 

l2geth logs:
```logs
2022-06-15T15:23:40.802 app[08d3d1a9] iad [info] WARN [06-15|15:23:40.802] Served eth_getBlockRange conn=[fdaa:0:6ec6:a7b:9d34:62b6:a25f:2]:44816 reqid=13952 t=138.77µs err="block in range not indexed, this should never happen" 
```

fault-detector logs:
```logs
2022-06-15T15:25:38Z app[62b6a25f] iad [info]{"level":50,"time":1655306738619,"extra":{"message":"processing response error (body=\"{\\\"jsonrpc\\\":\\\"2.0\\\",\\\"id\\\":14040,\\\"error\\\":{\\\"code\\\":-32000,\\\"message\\\":\\\"block in range not indexed, this should never happen\\\"}}\\n\", error={\"code\":-32000}, requestBody=\"{\\\"method\\\":\\\"eth_getBlockRange\\\",\\\"params\\\":[\\\"0xa6dff0\\\",\\\"0xa6e3ba\\\",false],\\\"id\\\":14040,\\\"jsonrpc\\\":\\\"2.0\\\"}\", requestMethod=\"POST\", url=\"http://l2geth.internal:8545\", code=SERVER_ERROR, version=web/5.6.1)","stack":"Error: processing response error (body=\"{\\\"jsonrpc\\\":\\\"2.0\\\",\\\"id\\\":14040,\\\"error\\\":{\\\"code\\\":-32000,\\\"message\\\":\\\"block in range not indexed, this should never happen\\\"}}\\n\", error={\"code\":-32000}, requestBody=\"{\\\"method\\\":\\\"eth_getBlockRange\\\",\\\"params\\\":[\\\"0xa6dff0\\\",\\\"0xa6e3ba\\\",false],\\\"id\\\":14040,\\\"jsonrpc\\\":\\\"2.0\\\"}\", requestMethod=\"POST\", url=\"http://l2geth.internal:8545\", code=SERVER_ERROR, version=web/5.6.1)\n    at Logger.makeError (/opt/optimism/node_modules/@ethersproject/providers/node_modules/@ethersproject/logger/src.ts/index.ts:261:28)\n    at Logger.throwError (/opt/optimism/node_modules/@ethersproject/providers/node_modules/@ethersproject/logger/src.ts/index.ts:273:20)\n    at /opt/optimism/node_modules/@ethersproject/providers/node_modules/@ethersproject/web/src.ts/index.ts:329:28\n    at step (/opt/optimism/node_modules/@ethersproject/providers/node_modules/@ethersproject/web/lib/index.js:33:23)\n    at Object.next (/opt/optimism/node_modules/@ethersproject/providers/node_modules/@ethersproject/web/lib/index.js:14:53)\n    at fulfilled (/opt/optimism/node_modules/@ethersproject/providers/node_modules/@ethersproject/web/lib/index.js:5:58)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","code":"SERVER_ERROR"},"msg":"caught an unhandled exception"}
```

**Comment by smartcontracts** [comment]
Ah yeah I noticed this the other day. I think it's a bug in l2geth. Going to investigate.

**Comment by stas** [comment]
Nice, happy to test it in the upcoming release :bow:

**Comment by smartcontracts** [comment]
@stas I think this should be released now. Can you try `docker compose pull` to download the latest images then restarting your node to see if the errors persist?

**Comment by stas** [comment]
@smartcontracts apologies for the late reply on this one. We ended up dropping the idea of running our own node atm (costs vs. men hours).

We were running the node on fly.io, which was quite interesting. 
We've open sourced our findings and config files in case somebody finds it interesting...
https://github.com/velodrome-finance/optimism-node

The costs can probably be wayyy lower if run on a bare metal server, but again, the beauty of something like fly.io is that you can scale horizontally very easy. They also provide built-in grafana services for any project, which is also very nice!

Thanks again for sharing all your work on this, really helpful! :heart:

**Comment by smartcontracts** [comment]
@stas this is really great feedback, thanks! Looking at your repo, I agree that initial sync is way to slow right now :-/ this problem basically goes away entirely with Bedrock. At one point I wrote a highly optimized experimental node that synced in a day or so but it wasn't worth the effort to get that into production simply because Bedrock is so close. Main issue is that we're using archive mode so the node syncs all the way from genesis. Problem is compounded by the fact that we have 1 tx per block so there's a lot of block processing that goes on between every transaction. Anyway, I'm sorry this didn't work for you. Bedrock will be significantly easier to run!

**Comment by stas** [comment]
@smartcontracts no regrets! I love the project you put together and wish we could have enough hours to invest into running our own nodes. Hopefully by the time Bedrock is out we can make time and go back to the idea of running our own RPCs :crossed_fingers: :hugs:
